AllCops:
  Exclude:
    - "bin/bundle"
    - "db/schema.rb"
  NewCops: disable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "app/components/**/*"

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
